mfussenegger/nvim-dap

- doc/dap.txt
- lua/dap.lua
- lua/dap/repl.lua
This implements the basic functionality of up/down, i.e. jump to a different frame in stack.
What is not (yet) implemented is to execute stepping commands relative to current frame. One possibility would be to issue multiple 'stepOut' request until the debugger reaches the current frame before performing the actual stepping. Since this is a bit a hack, I omitted it from this PR.
I noticed, that with the current dictionary approach the users must update their config when new repl commands are added. So either the documentation should be changed to recommend something like this 
```lua
dap.repl.commands.continue = {'continue', '.c'}
dap.repl.commands.next_ = {'next '}
```
or we reverse the look-up direction of this dict (see https://github.com/mfussenegger/nvim-dap/pull/8#issuecomment-626174 …
> Add `dap.up` and `dap.down`

- README.md
- doc/dap.txt
- lua/dap.lua
- lua/dap/repl.lua
- Add a `.goto` repl command. E.g. `.goto 10` to jump to line 10. This is supported by debugpy. Debugpy ignores all other arguments.
- Add `dap.goto_({line}`) to jump to line under cursor or a specific line.
In theory, the debug server could offer more than one jump target. I am just taking the first one if any. 
This request retrieves the possible goto targets for the specified source location.
These targets can be used in the ‘goto’ request.
Clients should only call this request if the capability ‘supportsGotoTargetsRequest’ is true.
```
interface GotoTargetsRequest extends Request {
command: 'gotoTargets';
arguments: GotoTargetsArguments;
}
```
Arguments for ‘gotoTargets’ request.
```
interface GotoTargetsArguments {
/**
* The source location for which the goto targets are determined. …
```
> Add Goto command

- lua/dap/repl.lua
~~I guess you renamed: `_set_frame` to `_frame_set`.~~
~~This PR fixes up/down for that change.~~
Resets the `->` after pressing enter on a frame. ~~If it's to much complexity for this mini-feature I'll just drop the corresponding commit.~~
> Reset arrow after frame switch

- lua/dap/repl.lua
Can be useful if `repl.append` is used to output errors - if the errors
contain file names `gf` can be used on them if `path` is setup
correctly.
> Inherit path for repl from previous buf

- lua/dap.lua
Managed to get into a state where there was still a sign but the bp_info
entry got removed.
This changes the call-sites of `bp_info[bp.id]` to handle the nil case.
> Handle nil `bp_info[bp.id]`

- README.md
- doc/dap.txt
- lua/dap.lua
```lua
-- Ask user to stop on which kinds of exceptions
require'dap'.set_exception_breakpoints()
-- don't stop on exceptions
require'dap'.set_exception_breakpoints({})
-- stop only on uncaughted exceptions
require'dap'.set_exception_breakpoints({"uncaughted"})
-- stop on all exceptions
require'dap'.set_exception_breakpoints({"raised", "uncaught"})
```
TODO:
> Add support for exception breakpoints

- lua/dap.lua
In that branch, this table.concat was in line 905. 
Seems to be a similar case as https://github.com/nvim-treesitter/nvim-treesitter/pull/341/files
```
LuaJIT 2.1.0-beta3 -- Copyright (C) 2005-2017 Mike Pall. http://luajit.org/
JIT: ON SSE2 SSE3 SSE4.1 BMI2 fold cse dce fwd dse narrow loop abc sink fuse
> a = {1, 4, 5}
> table.concat({nil, 3})
stdin:1: invalid value (nil) at index 1 in table for 'concat'
stack traceback:
[C]: in function 'concat'
stdin:1: in main chunk
[C]: at 0x5624d470f1d0
> table.concat({nil, 'd'}, ' ')
stdin:1: invalid value (nil) at index 1 in table for 'concat'
stack traceback:
[C]: in function 'concat'
stdin:1: in main chunk
[C]: at 0x5624d470f1d0
```
> Filter out possible nil values before applying table.concat

- doc/dap.txt
- lua/dap/ext/vscode.lua
Allows to use the command:
lua require('dap.ext.vscode').load_launchjs()
Within a `init.vim` or similar to read configuration entries from
`.vscode/launch.json`
> Add a extension module for vscode launch.json files

- lua/dap.lua
So that the line where the debugger stopped is visible
> Open fold when jumping to a breakpoint

- lua/dap.lua
- lua/dap/log.lua
Lines is deprecated and optional in the spec, but without it setting breakpoints with `vscode-go` fails.
Without the `name` in source it also rejected the breakpoints.
> Make vscode-go happy: Send source.name and lines in breakpoints

- README.md
- doc/dap.txt
- lua/dap.lua
- lua/dap/repl.lua
Reading the DAP docs, I guess `stepBack` and `reverseContinue` just work as the normal stepping commands.
Didn't find the time yet to test with `lldb-vscode`+`rr` or with https://github.com/Microsoft/vscode-mock-debug.
> Add support for reverse debug

- lua/dap/repl.lua
The signatures changed in https://github.com/neovim/neovim/commit/d3302573ba5f117fe7e1316be27321c3d9ffd261
Updated docs: https://github.com/neovim/neovim/pull/12860
> Update extmark calls to new API → fix .frames handling

- lua/dap.lua
When nvim-dap uses one of the windows in a background tab the user might not see that the current line cursor was set.
Maybe we could even open the window in a split if no non-special window was found in current tabpage (e.g. repl is the only window). But I don't know whether this would be expected.
```lua
for _, win in pairs(api.nvim_tabpage_list_wins(0)) do
local winbuf = api.nvim_win_get_buf(win)
if api.nvim_buf_get_option(winbuf, 'buftype') == '' then
local bufchanged, _ = pcall(api.nvim_win_set_buf, win, bufnr)
if bufchanged then
api.nvim_win_set_cursor(win, { frame.line, frame.column - 1 })
with_win(win, api.nvim_command, 'normal zv')
return
end
end
end
-- after that loop a split?
```
> Fix #61: Always ensure a window of the current tabpage is used on stop

- lua/dap.lua
When debugging C++, this would avoid setting current frame to
a frame without source information. But instead go directly to
to lowest one with source code.
Should this behavior be configurable?
Example:
```
___lldb_unnamed_symbol9102$$libnvidia-glvkspirv.so.455.23.05
___lldb_unnamed_symbol8912$$libnvidia-glvkspirv.so.455.23.05
___lldb_unnamed_symbol8997$$libnvidia-glvkspirv.so.455.23.05
___lldb_unnamed_symbol8998$$libnvidia-glvkspirv.so.455.23.05
___lldb_unnamed_symbol8999$$libnvidia-glvkspirv.so.455.23.05
___lldb_unnamed_symbol9000$$libnvidia-glvkspirv.so.455.23.05
_nv008nvvm
___lldb_unnamed_symbol51423$$libnvidia-glcore.so.455.23.05
___lldb_unnamed_symbol50266$$libnvidia-glcore.so.455.23.05
___lldb_unnamed_symbol50267$$libnvidia-glcore.so.455.23.05 …
```
> Skip frames without source when setting frame on stop

- lua/dap.lua
- lua/dap/ui.lua
This will make it easier to monkey patch pick_one with a nicer
implemention. Most fuzzy finders are operating async with callback as
they make use of popups.
An alternative example implementation is available in nvim-fzy[1] that can
be used like this:
lua require('dap.ui').pick_one = require('fzy').pick_one
[1]: https://github.com/mfussenegger/nvim-fzy
> Make pick_one function callback based

- doc/dap.txt
- lua/dap.lua
This will allow to run pre-hooks or start the adapter differently
depending on options in the configuration.
For example, debugpy has an example in the wiki[1] that translates to
roughly the following adapter implementation:
```lua
dap.adapters.python = function(cb, config)
if config.request == 'attach' then
cb({
type = 'server';
port = config.port or 0;
host = config.host or '127.0.0.1';
})
else
cb({
type = 'executable';
command = HOME .. '/.virtualenvs/tools/bin/python';
args = { '-m', 'debugpy.adapter' };
})
end
end
```
[1]: https://github.com/microsoft/debugpy/wiki/DAP-Client-reference#vs-code-debugadapterdescriptor
> Give the adapter function access to the config

- lua/dap.lua
To avoid things like done in [debugpy][1] from affecting neovim
Should fix #59
[1]: https://github.com/microsoft/debugpy/commit/5087603ea3db9596960d7477633ba189debda1c6
> Spawn child process detached

- lua/dap.lua
Otherwise `not xy` may not evaluate to false, because `xy` may be `vim.NIL`.
Required to get haskell-debug-adapter working.
> Normalize vim.NIL to nil in dap responses

- doc/dap.txt
- lua/dap/repl.lua
Allows users to customize where the REPL is opened.
An example use:
:lua require('dap').repl.open({ wincmd = 'vsplit' })
Closes https://github.com/mfussenegger/nvim-dap/issues/79
---
**Update**
Changed it to `open(<winopts>, <wincmd>)`:
:lua require('dap').repl.open({}, 'vsplit')
> Add a `wincmd` argument to repl.open/toggle

- doc/dap.txt
- lua/dap.lua
- lua/dap/log.lua
Follows the upstream change, so that the `dap.log` is in the same folder
as the `lsp.log`:
https://github.com/neovim/neovim/commit/ea8756f85ddd0aeed2e7eccd0ea86ade4fb7eca8
> Change logfile path to XDG_CACHE_HOME

- syntax/dap-variables.vim
I think this line is not needed any more since I copied the number matches from python.vim
> fix(variables): remove erroneous syntax match

- doc/dap.txt
- lua/dap/ui/variables.lua
- syntax/dap-variables.vim
Add a function to toggle multiline display in the variable hover window (also available as `?` keymap in hover window). Useful for inspecting stacktraces and multi-line strings. Some object representations can get pretty long this is why single line display is the default.
https://user-images.githubusercontent.com/7189118/105631194-87df8e80-5e4d-11eb-95f6-aa31a42a3d38.mp4
https://user-images.githubusercontent.com/7189118/105631183-7f875380-5e4d-11eb-8b6d-4a10ecb2d626.mp4
> feat(variable hover): add function to toggle multi-line display

- lua/dap.lua
After https://github.com/neovim/neovim/commit/e85c8dff692c894a614192f6dd8a4c71c1c9fe30
passing an empty list as `env` became an error.
> Ensure the env passed to spawn is a dictionary

- .github/workflows/linter.yml
Bad abstractions are worse than a bit of code duplication
> Disable jscpd linting

- doc/dap.txt
- lua/dap/ui/variables.lua
- lua/dap/utils.lua
New default for evaluation expression is visual selection or `cword`
This enable inspecting of member functions without explicit `this`
Or evaluation from visual selection
when selecting `this->m_member`
The functions for visual selection come from nvim-treesitter. I wrote the one that gives you the text from the range.
You can replace the function for the current expression to evaluate if you want to.
> variables: Enable dynamic evaluation with customizable function

- lua/dap.lua
`nvim_win_get_cursor` returns a 0-indexed column position, but the debug
adapter expects a 1-indexed column position.
> Fix off by 1 error in omnifunc

- doc/dap.txt
- lua/dap/ext/autocompl.lua
This is quite minimal, all it does is trigger the omnifunc if any of the
trigger characters is typed in insert mode.
The dap omnifunc implementation is async, so this is non-blocking and
should be fast.
This should provide a good experience without dap turning into a full
blown autocompletion plugin.
It is opt-in so users could also use their prefered completion plugin with the omnifunction
https://user-images.githubusercontent.com/38700/107116178-c889cf80-6871-11eb-80d3-02a558ef21d1.mp4
> Add a trigger character based autocompletion extension

- lua/dap.lua
The change to use vim.empty_dict() was necessary for jobstart but
not for uv.spawn. This prevented me from starting debugpy.
> fix: do not pass vim.empty_dict() to uv.spawn

- lua/dap/ui/variables.lua
Hi @mfussenegger ,
Thanks for providing this nice plugin!
I've noticed, that you use `<cword>` for the hover functionality. This doesn't work well for nested properties, e.g.
```js
myObject.myProperty
//       ^^^^^^^^^^ you hover here
```
In this example, `hover` would be called with `myProperty` leading to an error.
Vim has also `<cexpr>` which does the trick, yielding `myObject.myProperty`.
See `:h <cexpr>` for more information.
I've created this PR to change the behaviour, feel free to reach out to me if you have any questions.
I also created a small video showing this in action:
https://youtu.be/ga3Cas7vNCk
Best regards,
David
> Hover: Use <cexpr> instead of <cword>

- lua/dap.lua
Avoids having an additional window open each time a debug session starts
Not sure if there should be a configuration option to keep the old behavior?
Somebody might want to compare outputs or something like that?
> Wipe old terminal buffer before creating a new one

- lua/dap.lua
delve always returns 0 as `seq` in their reponses, that reset the
counter and led to duplicate `request_seq` numbers, which broke the
callback selection.
> Do not set seq based on server responses

- doc/dap.txt
This little line caused me some unfortunate headaches in setting up my mappings :sweat_smile:
> fix: dapl.repl.run_last to dap.run_last in example mappings

- doc/dap.txt
- lua/dap.lua
As discussed in https://github.com/mfussenegger/nvim-dap/pull/124 this
gives users the possible to choose whether the listeners should be
called before or after the internal listeners.
I also used the opportunity to add another change: The response
listeners are now also called in error cases. So the number of arguments
changed.
`custom_event_handlers` and `custom_response_handlers` are both still
there and used. (Without the signature change for request responses)
If used a warning will be printed out.
They'll be removed at some point in the future.
> Add listeners.{before,after} as replacement for custom_ handlers

- lua/dap.lua
I have been playing around with nvim-dap and an lua adapter for it. TCP communication got me stuck for a good moment but I think this fixes it. This calls `read_start` once in the `connect` callback. Similar to [here](https://github.com/luvit/luv/blob/master/examples/uvbook/tcp-echo-client.lua).
> fix: call read_start once connected

- doc/dap.txt
- lua/dap.lua
- lua/dap/repl.lua
- lua/dap/ui.lua
Can be tested with: https://github.com/microsoft/debugpy/pull/563 (merged)
It will ask to step into which target if there are more stepInTargets in one line (makes more sense for list comprehensions than having multiple statements in one line). I added an option to not ask for step targets which would correspond to the old behavior.
> feat: Add support for stepInTargets

- lua/dap.lua
- lua/dap/repl.lua
Neovim master supports `v:lua.require'dap'` which can be used instead
for the omnifunc.
Closes https://github.com/mfussenegger/nvim-dap/issues/115
> Remove the `dap` global

- lua/dap.lua
- lua/dap/repl.lua
Should fix https://github.com/mfussenegger/nvim-dap/issues/119
If the repl is closed using `:bd` directly without force it will still fail if
the buffer is modified, but the `:qall`, `repl.close` and `repl.toggle` cases
work without error.
> Fix repl modified handling

- doc/dap.txt
- lua/dap.lua
- lua/dap/repl.lua
We could also keep the current behavior and but only accept target in the same line or the same statement. I just had the feeling that when you can step into any arbitrary function in the stack frame it would be different enough that the user would like to have both normal stepIn and stepIn with targets.
I don't know whether this is the best strategy. The protocol is very flexible on when its about what adapter should return and how debugger should use the response best in its UI.
> Fix #138: Make stepInTargets an explicit command

- lua/dap/session.lua
Lua lesson:
local bps = {}
bps[127] = {{ line = 170 }}
print(#bps)   -- prints 0
> Fix regression preventing breakpoints from being sent

- lua/dap.lua
This reverts commit 0419f02339cb18912ae510f9dcf91ede6f2b28d6.
Caused an error if `name` was nil and if cmdheight is 1 instead of 2 the
notifications can trigger a ENTER prompt.
Will instead add a progress function that can be used for integration in
the statusline.
> Revert "Add some progress notifications when launching a session"

- lua/dap/entity.lua
- lua/dap/repl.lua
- lua/dap/ui.lua
- tests/ui_spec.lua
A smaller subset of https://github.com/mfussenegger/nvim-dap/pull/165
One key difference to the previous tree-render logic is that this one supports refreshing the rendered tree with new values while keeping expanded items intact.
> Create a tree abstraction to render out variables

- doc/dap.txt
- lua/dap/repl.lua
- lua/dap/ui.lua
- lua/dap/ui/widgets.lua
- tests/ui_spec.lua
This allows users to show widgets (frames, scopes, evaluated expressions) in a
sidebar or in floating windows.
This is based on https://github.com/mfussenegger/nvim-dap/pull/165 but the
existing variables functionality is left untouched.
Once the widget functionality has feature parity the ui.variables functionality
could be deprecated and later removed.
https://user-images.githubusercontent.com/38700/117205777-5bdf8c00-adf2-11eb-9301-04a04c11e98f.mp4
> Add a widget api

- doc/dap.txt
- lua/dap.lua
- lua/dap/session.lua
Allow users to provide their own split command for opening a new window when using the integrated terminal.
A new property has been added to the configuration:  **windowSplit**.  If not provided, the default value of "belowright new" is used.
Example configurations:
```
require'dap'.configurations.python = {
{
type = 'python';
request = 'launch';
name = "Launch file";
console = "integratedTerminal";
windowSplit = 'botright 20new';
}
}
```
```
require'dap'.configurations.python = {
{
type = 'python'; 
request = 'launch';
name = "Launch file";
console = "integratedTerminal";
windowSplit = '40vsplit new';
}
}
```
> feat:  Add support for window split configuration

- lua/dap/ext/autocompl.lua
The first trigger becomes more aggressive, but subsequent are now
completely ignored until the first one finishes
> Tweak the debounce behavior for the repl autocompletion

- lua/dap/session.lua
The terminal might show stack traces which can contain file names with line
numbers.
If a user launches the debug session from a buffer that has a sensible
`path` set, this will enable the user to use `gf` or `gF` on these stack
trace entries to navigate to them.
> Try to preserve the `path` option when creating a terminal

- doc/dap.txt
- lua/dap.lua
- lua/dap/session.lua
Allows to override the `restart` and `terminateDebuggee` arguments
> Add opts argument to disconnect

- lua/dap/session.lua
"\#" lua operator return wrong result for dictionary like tables (with empty_dict metatable).
Also, `vim.tbl_count()` is better than `#`.
Fixes #191
```lua
-- https://github.com/neovim/neovim/blob/68d40388f356587726ea7db83f87846dfaecf9d9/runtime/doc/lua.txt#L650
-- Note: if numeric keys are added to the table, the metatable will be ignored and the dict converted to a list/array anyway.
local d
-- dictionary
d = vim.empty_dict()
print(vim.inspect(d))
d['k'] = 'v'
print(vim.inspect(d))
print('count #', #d) -- 0 element, what?
print('count vim.tbl_count()', vim.tbl_count(d)) -- 1 element
-- array
d = vim.empty_dict()
print(vim.inspect(d))
d[1] = 2
print(vim.inspect(d))
print('count #', #d) -- 1 element
print('count vim.tbl_count()', vim.tbl_count(d)) -- 1 element
```
As alternative, …
> Use vim.tbl_count() instead of non_empty

- doc/dap.txt
- lua/dap.lua
- lua/dap/breakpoints.lua
- lua/dap/session.lua
- The breakpoints are now kept, but the sign is updated
- If the server response contains a message, it is printed
- The quickfix list shows the rejected message if available
> Improve rejected breakpoints feedback

- doc/dap.txt
- lua/dap/session.lua
This can be useful for lldb-vscode where you can set `runInTerminal =
true` but don't have an option to choose between integrated and external
terminal.
https://user-images.githubusercontent.com/38700/121802503-ee1e4f80-cc3c-11eb-9616-e2e9b4aa52ee.mp4
> Add an option to force external terminal

- doc/dap.txt
- lua/dap.lua
This PR adds more predefined variables like `${file}` and `${workspaceFolder}` which should match VS Code examples defined [here](https://code.visualstudio.com/docs/editor/variables-reference#_predefined-variables-examples).
I was trying to create a Go Delve configuration that used `${fileDirname}` based off these [docs](https://go.googlesource.com/vscode-go/+/HEAD/docs/debugging.md#debug-a-single-test-function). I don't know if you have any interest in supporting all of these but they were simple enough to construct so I figured I'd include as many as I could.
With this variable I can now construct a config that looks like this to debug all tests within a package:
``` lua
{
type = "go",
name = "Debug package tests", -- configuration for debugging test files
request = "launch",
mode = …
```
> Add more predefined variables

- doc/dap.txt
The widget API should be used instead.
With the exception of the multiline toggle there should be feature
parity between the two.
> Remove variables API docs

- lua/dap/repl.lua
- lua/dap/ui.lua
During debugging (or when running junit tests with extensions like
nvim-jdtls) output may be written to the REPL. Previously this output
was discarded if the REPL wasn't open.
This commit changes the behavior to preserve the output until the next
debug session starts - or until the REPL was opened and is then closed
again.
> Keep repl.append content if repl is hidden

- lua/dap/session.lua
Should fix https://github.com/mfussenegger/nvim-dap/issues/228
> Use cwd from runInTerminal request for termopen call

- lua/dap/utils.lua
- tests/utils_spec.lua
Workaround for https://github.com/mfussenegger/nvim-dap/issues/225
> Allow null values as argument to to_dict

- lua/dap/ui.lua
This will allow `view.toggle()` to be used for terminal buffers without
interrupting the execution.
> Prevent view.toggle from deleting a buffer

- lua/dap/repl.lua
This reverts commit 12f208b4a6463c69d9140e1a6ce5806a552330f2.
`vim.trim()` also removes leading whitespace, which is not always what a
user may want.
For example, nvim-jdtls outputs stacktraces on the REPL.
With vim.trim(), this looks like follows:
❌testExecutionPhaseIdSequence
java.lang.AssertionError:
Expected: is <3>
but: was <0>
at __randomizedtesting.SeedInfo.seed([6ECD24DB888A0803:2DF3FE03A2B7ACE5]:0)
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
at org.junit.Assert.assertThat(Assert.java:964)
at org.junit.Assert.assertThat(Assert.java:930)
Reverting this change restores the previous behavior:
❌testExecutionPhaseIdSequence
java.lang.AssertionError:
Expected: is <3>
but: was <0>
at __randomizedtesting.SeedInfo.seed([C3CE5B0CBD15A42:4F023F68E1ECFEA4]:0)
at …
> Revert "repl lines issue use vim.trim()"

- lua/dap/ui.lua
There's an error raised if a REPL command returns no text. For example assigning a variable in python.
```
Error executing vim.schedule lua callback: ...ache/nvim/site/pack/packer/start/nvim-dap/lua/dap/ui.lua:407: end_col value outside rang
```
This is more of a quick fix suggestion that I found while testing, not sure if this how you would want to handle this
> fix(ui): handle empty text in repl

- lua/dap.lua
- lua/dap/session.lua
This adds a (as of now undocumented) `set_session` method that allows
extensions to change the active session with which the user facing
commands are interacting.
This is useful for extensions like nvim-dap-python because debug
adapters like debugpy contain custom extensions to the core debug
adapter protocol where they need to have multiple sessions running at
the same time.
Until multi-sessions become part of the official specification,
multi-session support is out-of-scope for nvim-dap, but this method
should be enough to allow extensions to do the remaining work.
(The UX may not be ideal because breakpoints are global and there exists
no breakpoint - session mapping, but it should at least make it possible
to get things working in some way)
> Allow to override the active session

- lua/dap/repl.lua
- lua/dap/session.lua
To ensure that it always uses the active session of the dap module.
> Remove session local from repl

- .luacheckrc
- doc/dap.txt
- lua/dap.lua
- lua/dap/session.lua
- tests/integration_spec.lua
dap.stop() is still kept, but will emit a message that it is
deprecated.
This also changes the default for `terminateDebuggee` in `disconnect` to
`nil` - which means the behavior is up to the debug adapter.
> Rename dap.stop() to dap.close() and clarify docs

- lua/dap/repl.lua
Fixes https://github.com/mfussenegger/nvim-dap/issues/237
> Use layer.render to clear REPL to remove extmarks

- lua/dap/session.lua
Since 11291a4a01fa43e8b1b51d522c7cd7788147056f Session:initialize can be
called in the luv event-loop, and repl.clear must run in the main loop
> Ensure repl.clear is run in main loop

- doc/dap.txt
- lua/dap/repl.lua
1. Make it clear in the example that one must require "dap.repl" before
extending the dap.repl.commands table; otherwise the lazy-loaded repl
won't see the custom commands in the extended table, even though the
changes are visible to vim.inspect().
2. Also make it clear what you can or cannot hope to do by extending the
commands table: you can add aliases for existing builtin commands
(but not override them), you can hook up a new command to an existing
dap function, or define an entirely new custom command as a function
(and you only need to override what you want to change).
3. Earlier, the code would invoke the custom command with the whole of
the command text, i.e., ".echo hello world". On the basis that it's
inconvenient for every custom command to have to always strip the
command …
> Clarify how to use dap.repl custom_commands

- lua/dap.lua
`spawn` and `connect` could fail - if that is the case `session` didn't
get re-assigned but was kept in a closed state. A second `:close` call
resulted in errors.
> Ensure closed sessions aren't re-used

- lua/dap/session.lua
There's currently an issue on neovim master that causes loading
(uncached) modules within a luv callback to crash neovim.
This moves the `require(dap.repl)` call to the top of the session - the
session itself is already lazy loaded and it should be fine to pull in
all dependencies in that case.
> Avoid repl lazy loading to avoid crash on latest master

- lua/dap/session.lua
Following up on the convo in
https://github.com/mfussenegger/nvim-dap/discussions/314#discussioncomment-1381937
I figured I'd quickly just bump this from 2 -> 4. It might be just
bumping this a bit like this gets rid of the need to even have this
configurable.
> Double the default timeout period for session.

- doc/dap.txt
Seems like this is what GitHub looks for to set some highlights on the web viewer.
https://github.com/neovim/neovim/blob/9337fff8aad610acd5ef619f757686c47f0c118c/runtime/doc/api.txt#L2857
> fix: enable syntax highlighting when viewing on github

- lua/dap/ui/variables.lua
The docs got already removed quite some time ago.
This adds a warning and in a couple weeks I'll remove the module.
> Add deprecation warnings to ui.variables functions

- lua/dap.lua
Both breaking change and bugfix, see
https://github.com/mfussenegger/nvim-dap/issues/351 for context.
Without this change, the value of `${file}` depends on how you open a
file. `:e myFile` will resolve to `myFile` and `:e /path/to/myFile`
resolves to `/path/to/myFile`.
After this change `${file}` will always return the absolute path,
independent of how you open a file.
Side effect of this is that it breaks usages of
`${workspaceFolder}/${file}`.
> Ensure ${file} maps to absolute path and {$relativeFile} to relative path

- doc/dap.txt
- lua/dap/entity.lua
- lua/dap/repl.lua
- lua/dap/ui.lua
- lua/dap/ui/widgets.lua
Mostly to introduce the concept of having multiple actions per item in a widget.
Doesn't add too much meaningful functionality - the debug adapters I tested with struggle with `setVariable` and `setExpression`. Using `evaluate` via the REPL is easier and works better.
Data breakpoints might be a candidate for adding next
> Add set-expression/set-variable widget actions

- lua/dap/repl.lua
- lua/dap/ui.lua
- lua/dap/ui/widgets.lua
After 16c22742df0c358a7f95ded813c08f98f5c42031 `<CR>` on frames no
longer jumped to the frame but instead resulted in a message that there
is no action on the frame.
> Fix jump to frame in frames widget regression

- lua/dap.lua
The variable expansion dropped metatables. That turned a `vim.empty_dict`
into a `{}` which gets serialized as list.
Fixes https://github.com/mfussenegger/nvim-dap/issues/378
> Ensure vim.empty_dict in config serializes as object

- lua/dap/ui/widgets.lua
The frames widget only updated on `event_stopped`, that missed active
frame changes - like via `.down` or `.up`.
`scopes` is called after each frame change.
Closes https://github.com/mfussenegger/nvim-dap/issues/390
> Update frames widgets on scopes changes

- lua/dap/ui/widgets.lua
This is the same strategy employed by the scopes widget.
Closes #404.
> Use a fallback frame value for expression widget

- lua/dap.lua
If the debug adapter configuration is broken the session may not
initialize fully but be left in a semi-initialized state.. Terminate
should still work despite that.
> Handle nil capabilities in terminate

- lua/dap/session.lua
Earlier versions (I think < 1.41) had an issue with the `protocol`
parameter)
> Resolve DNS only on luv >= 1.42.0

- lua/dap/session.lua
Workaround for problems reported in https://github.com/mfussenegger/nvim-dap/issues/402
> Fallback to connection without hostname lookup if getaddrinfo fails

- lua/dap/ui/widgets.lua
This makes it easier to setup custom mapping or change other buffer
options in a `filetype/dap-float.{lua,vim}` file.
> Set dap-float filetype in floating widgets

- doc/dap.txt
- lua/dap.lua
- lua/dap/session.lua
adds option to focus the terminal when it's opened (default to `false` which is the current behaviour).
> feat(session) adds focus_terminal option

- lua/dap/repl.lua
- lua/dap/ui.lua
- tests/ui_spec.lua
I'm not sure yet if this behavior is better. Happy to get some feedback
> Remove trailing newline when rendering variables

- .luacheckrc
- lua/dap/session.lua
https://github.com/mfussenegger/nvim-dap/pull/425 caused a regression.
Fixes https://github.com/mfussenegger/nvim-dap/issues/442
> Don't jump to nofile buffers unless it's a dap-source scratch buffer

- lua/dap/session.lua
Without this flag VS code plugin was crashing on adding breakpoints.
I am not sure about making it always false though. I have no idea how to detect that.
> Added sourceModified flag to payload to make Unity debugger work

- lua/dap/repl.lua
Looks like using appendbufline can cause hiccups and trigger events for
other buffers.
Closes https://github.com/mfussenegger/nvim-dap/issues/465
> Use nvim_buf_set_lines instead of appendbufline in repl.append

- README.md
> Remove DAPInstall reference from readme

- lua/dap.lua
- lua/dap/progress.lua
- lua/dap/session.lua
- tests/integration_spec.lua
- tests/server.lua
Regular callbacks are scheduled in the main event loop. The same should
be done with if the callback is triggered due to a timeout to ensure
vimL functions can be used.
Fixes:
nvim-dap/lua/dap/session.lua:846: E5560: vimL function must not be called in a lua loop callback
stack traceback:
[C]: in function 'sign_unplace'
...nvim-dap/lua/dap/session.lua:846: in function 'close'
...nvim-dap/lua/dap/session.lua:991: in function 'callback'
...nvim-dap/lua/dap/session.lua:880: in function <...nvim-dap/lua/dap/session.lua:872
> Run disconnect timeout callback in main loop

- lua/dap/ui/widgets.lua
Makes it easier to navigate to the different widgets if they're kept
open.
> Add buffer names to hover, scopes and frames widgets

- doc/dap.txt
- lua/dap.lua
- lua/dap/entity.lua
- lua/dap/session.lua
- lua/dap/ui.lua
- lua/dap/ui/widgets.lua
- lua/dap/utils.lua
- tests/debugpy_spec.lua
Changes the threads management slightly so that threads are only updated on a stopped event if they're dirty (new threads started or some exited). This should make stepping a bit faster if there are many threads.
This now also allows to have several stopped threads in parallel. By default only if threads are manually paused. Stopped events due to exceptions or breakpoints will still get continued automatically if there is already a stopped thread used for stepping around.
https://user-images.githubusercontent.com/38700/161313066-236947ed-0340-4b97-9dc1-b3f0d70e6d53.mp4
> Add a threads widget

- lua/dap.lua
- lua/dap/session.lua
- tests/integration_spec.lua
Consider the scenario below:
1. User sets Breakpoint 1 in Buffer A
2. User sets Breakpoint 2 in Buffer A, which is a few lines below
Breakpoint 1
3. User starts debugging
4. User opens Buffer B, in which a method is supposed to be called after
Breakpoint 1 and 2
5. User uses run_to_cursor in Buffer B
Issues with current implementation:
1. Program will pause at Breakpoint 2 prior to cursor line in Buffer B,
since breakpoints in Buffer A are not cleared
2. Temporary breakpoint in Buffer B will not be cleared, since Buffer B
was not in the list of buffers that've got breakpoints before the
run_to_cursor operation, and it hasn't got other breakpoints after
run_to_cursor either
This PR fixes the above issue by sending setBreakpoints requests for all
involved buffers.
---
I'm new to Lua so …
> Unset breakpoints globally when run_to_cursor

- .github/workflows/tests.yml
- README.md
With the release of 0.7.0 it is time to move on.
> Drop support for neovim 0.5.1; Add 0.7.0 to CI matrix

- lua/dap/session.lua
The command in the args is often the debug-adapter executable, or a
runtime like python/java, etc. Using the config name is probably more
useful.
> Use config name in integrated terminal buffer name

- lua/dap/session.lua
Adds fix for precedence operation that was not taken into account. On master at the moment the concat takes precedence over the OR operator which was causing a runtime error when the config.name was null, due to trying to concat a nil value.
> Fix the precedence operation in session.lua.

- lua/dap/session.lua
Both `lldb-vscode` and `vscode-cpptools` set both `threadId` and `allThreadsStopped` to `true` after exception/segfault, this was causing the program to continue when trying to expand (in repl's `.threads`) any thread apart from `threadId`
This PR fixes it by checking for `allThreadsStopped` first and then `threadId`
> Fix corner case when both threadId and allThreadsStopped are set

- lua/dap/session.lua
Some debug adapters don't play nice and send neither an error nor a
response if setting breakpoints if the sessions is just getting
terminated.
This can happen if you disconnect and immediately remove a breakpoint.
> Handle nil response on setBreakpoints

- lua/dap/session.lua
filetype.match no longer sets the filetype itself: https://github.com/neovim/neovim/pull/18894
> Adjust filetype.match usage to nightly changes

- lua/dap/session.lua
The notify was intended for edge cases, assuming that there would be no
jump action, but 688cb52d8bfbb237531056b24d727f33ff4bedfa changed that
and made it more common.
> Remove notify call on allThreadsStopped

- lua/dap/session.lua
Looks like this might be a workaround for https://github.com/mfussenegger/nvim-dap/issues/589
> Avoid table.concat call in integrated terminal

- tests/integration_spec.lua
The monkey patching in the test messed with lua-language-server, leading
to false warnings about the number of parameters.
> Workaround lua-language-server vim.notify warning

- lua/dap/session.lua
Debugging something and deleting the terminal buffer before the
process exits caused `Invalid channel id` errors because the output of
the process can no longer be sent to the terminal buffer.
This mutes the messages.
> Fix Invalid channel id errors if terminal buffer is deleted

- doc/dap.txt
- lua/dap.lua
- lua/dap/session.lua
- lua/dap/utils.lua
- tests/integration_spec.lua
- tests/run_server.lua
- tests/server.lua
- tests/server_executable_spec.lua
This makes the adapter definition for adapters that don't support STDIO
but only TCP a bit easier. For example, for delve it reduces the adapter
definition to:
```lua
dap.adapters.delve = {
type = 'server',
port = '${port}',
executable = {
command = 'dlv',
args = {'dap', '-l', '127.0.0.1:${port}'},
}
}
```
> Extend server adapter definition to support spawning executable's

- lua/dap/session.lua
Pressing enter when inputting using the same terminal buffer will prematurely delete the buffer mid-session.
Related https://github.com/rcarriga/nvim-dap-ui/issues/120
> fix(terminal): disable bd mapping until complete

- lua/dap/session.lua
If you position the cursor over a variable in anticipation of hitting
the breakpoint to inspect it, it's a bit annoying if it jumps to the
first column.
> Keep cursor position if already at jump location

- doc/dap.txt
- lua/dap.lua
- lua/dap/utils.lua
This would allow using stuff like `vim.ui.select` within the
configuration values.
The requirements are:
- The function must return a coroutine
- The coroutine must resume the **outer** coroutine with the result
An example:
```lua
foo = function()
return coroutine.create(function(dap_run_co)
local items = {'one', 'two'}
vim.ui.select(items, { label = 'foo> '}, function(choice)
coroutine.resume(dap_run_co, choice)
end)
end)
end,
```
> Support thread values in configuration evaluation

- lua/dap/session.lua
This can be used by scripts or similar to process the terminal buffers
output depending on the config type. If a session ended, the information
is otherwise no longer available.
For example, one could parse the output of `python unittest` into the
quickfix list with something like this:
```lua
local efms = {
python = [[%C %.%#,%A  File "%f"\, line %l%.%#,%Z%[%^ ]%\@=%m]],
}
function M.load()
local buf = api.nvim_get_current_buf()
local ft = vim.b[buf]['dap-type'] or vim.bo.filetype
local efm = efms[ft] or vim.bo.errorformat or vim.g.errorformat
local lines = api.nvim_buf_get_lines(buf, 0, -1, true)
vim.fn.setqflist({}, 'r', { efm = efm, lines = lines })
end
```
> Add a `dap-type` buffer variable to terminal buffers with the `config.type` value

- lua/dap/session.lua
Can avoid an extra threads request on a following stopped event.
> Don't mark threads as dirty if a known thread starts

- lua/dap/ui/widgets.lua
Makes sure `vim.keymap.set('v', lhs, require('dap.ui.widgets').hover)`
works as expected and makes it unnecessary to use something like this
instead:
[[<ESC><CMD>lua require'dap.ui.widgets'.hover(require("dap.utils").get_visual_selection_text)<CR>]]
> Use selection as expression if calling hover or preview in visual mode

- lua/dap/ui/widgets.lua
Closing the preview window via `CTLR-w z` / `:pclose` shouldn't leave
stale buffers.
> Set bufhidden=delete for preview window buffer

- lua/dap/session.lua
- lua/dap/ui.lua
If running within a coroutine the callback argument can now be omitted
to get the result as return value.
This can be utilized to avoid nesting via multiple callbacks if a method
requires multiple requests.
> Make session:request coroutine aware

- lua/dap/session.lua
- lua/dap/ui.lua
Error messages reported by `error` or `assert` calls could go unnoticed
depending on the `vim.ui.select` implementation.
Scheduling the callback should avoid that.
> Schedule pick_one callback to ensure error messages are visible

- tests/ext_vscode_spec.lua
Otherwise lua-language-server gets confused and reports warnings about
vim.fn.input calls with more than 2 arguments
> Add third param to fn.input mocks

- doc/dap.txt
- lua/dap.lua
if a sign is already set in some user config we do not overwrite the value and skip it. This enables sign configuration by the user regardless where the user requires the dap plugin. This is kind related to the closed issue #76
> user config aware sign define

- doc/dap.txt
- lua/dap/ext/vscode.lua
Closes https://github.com/mfussenegger/nvim-dap/issues/650
> Expose `json_decode` for overrides in ext.vscode

- lua/dap/session.lua
Mostly just as a debugging aid to implement multi-session support and
identify sessions
> Add an id to sessions

- lua/dap/session.lua
Should help ensure the global value is left unmodified.
> Set terminal window options with scope = local

- lua/dap.lua
A list of breakpoints replaces the current quickfix list only if the current quickfix list is a list of breakpoints.  A quickfix list of breakpoints is recognized by the title.  If the title is the same as the title nvim-dap assigns then the list is counted as a quickfix list of breakpoints.  If the current quickfix list consists of something else like results from Telescope or make then the list is saved in the history and nvim-dap creates a new one.
> Breakpoints quickfix list smart replace.

- lua/dap/ext/vscode.lua
- plugin/dap.lua
This adds two autocmds.
The first one will pre-fill the content of a `.vscode/launch.json` file if it doesn't already exist to have the boilerplate ready.
The second one will automatically re-read the configurations from the `vscode/launch.json` if you modified it and are saving the changes.
This may be a bit controversial so I'll leave this open for a while and would appreciate feedback. (Use thumbs up/down, please leave comments if you have a strong opinion and rationale why it shouldn't be merged)
Alternatives:
- Add as cookbook entry to the Wiki
- Don't add the autocmds per default, but require opt-in via a `require('dap.ext.vscode').setup()`
> Add templating support for launch.json and auto-load on save

- doc/dap.txt
- lua/dap.lua
Hi, I added the env variables support similar to [vscode](https://code.visualstudio.com/docs/editor/variables-reference#_environment-variables).
> Add support for env variables reference.

- lua/dap/session.lua
I noticed that sometimes when opening (jumping to) a stack frame in nvim-dap-ui the cursor position is incorrect. Using `nvim_win_call` instead of changing windows fixed the issue.
> Fix incorrect cursor position when opening frame from dapui

- lua/dap/session.lua
There may not be a thread anymore for the `stopped_thread_id`.
That resulted in an error.
An alternative could be to reset the `stopped_thread_id` and assume it
is not stopped anymore, but not sure if that is safe.
> Handle missing thread in auto_continue handling

- lua/dap/session.lua
- tests/integration_spec.lua
- tests/server.lua
So far the exception info was shown in the REPL, but users may have the
REPL closed in which case they don't see the exception details.
This instead uses the diagnostic API to add the exception details as an
error.
> Show exception info on stopped via diagnostic

- lua/dap/session.lua
Continually run into the following error when restarting a debugging session:
```
Error executing vim.schedule lua callback: /usr/share/nvim/runtime/lua/vim/diagnostic.lua:1458: Invalid buffer id: 22
stack traceback:
[C]: in function 'nvim_exec_autocmds'
/usr/share/nvim/runtime/lua/vim/diagnostic.lua:1458: in function 'reset'
/home/louis/.config/nvim/after/nvim-dap/lua/dap/session.lua:1399: in function 'close'
/home/louis/.config/nvim/after/nvim-dap/lua/dap/session.lua:703: in function 'callback'
/home/louis/.config/nvim/after/nvim-dap/lua/dap/session.lua:958: in function </home/louis/.config/nvim/after/nvim-dap/lua/dap/session.lua:950>
```
Swapping the session close and the reset of the namespace in session.lua seems to fix the issue.
Signed-off-by: Louis DeLosSantos …
> fix: invalid buffer is on diagnostic reset

- lua/dap/session.lua
- Allow to switch current tabpage if the buffer is open in another tab
- Change current active window/buffer, if all else failed instead of
printing a warning
> Make jump to stopped location more aggressive

- doc/dap.txt
- lua/dap/session.lua
Allows users to distinguish between their own requests and other requests when listening.
The motiviation for this is that nvim-dap maintains some state internally for its functionality (e.g. session.current_frame) which nvim-dap-ui needs to be aware of so users don't have issues with the two plugins showing different information. Some of this state is set after requests such as `stackTrace` for the current frame. nvim-dap-ui needs to listen for this and refresh after it has been processed. Issues arise when the listener causes more stack trace requests, leading to infinite recursive calls because the listener can't distinguish between calls made by nvim-dap and itself.
This is occurring now because of a large refactor of nvim-dap-ui which moves away from maintaining state (which …
> feat(session): pass request seq to callbacks/listeners

- lua/dap/session.lua
following up from #803, @mfussenegger do you think we can use the standard setting instead of a global variable?
> feat(switchbuf): use setting instead of variable

- lua/dap.lua
- lua/dap/session.lua
In preparation for multiple/hiearhical sessions which will be required
for the `startDebugging` reverse request.
With a global namespace we'd clear signs and diagnostics of all sessions
if one exits. That's a problem.
> Add namespace pool and use per-session namespace for signs/diagnostic

- lua/dap/breakpoints.lua
- lua/dap/session.lua
If the client sends a terminate the debug adapter can send the response,
terminate event and terminate the debug adapter process. In that case
the client immediately closed the stdout handle and cleared the message
callbacks table, preventing it from reliably processing the last few
messages.
This makes use of the async stdout:shutdown/client:shutdown to give it a
chance to process these last messages.
This is a follow up to
https://github.com/mfussenegger/nvim-dap/commit/03807a4682081cc2523219ef17a36a618995b36d
and should ensure that event_terminated listeners triggers happen in
most (all?) cases.
> Increase chance to trigger request callbacks on debug adapter exit

- lua/dap.lua
- lua/dap/protocol.lua
- lua/dap/session.lua
- tests/integration_spec.lua
Not sure which debug adapters make use of this.
Basic implementation that shows title and message in the `status()`
function.
This will also allow extensions to subscribe to the events and display
the information in more sophisticated ways.
> Add supportsProgressReporting capability

- lua/dap/ext/vscode.lua
- tests/ext_vscode_spec.lua
Fixes https://github.com/mfussenegger/nvim-dap/issues/837
> Allow underscore in id of `${input:<id>}`

- lua/dap/repl.lua
Any objections to setting the REPL to unlisted? It's a common issue for nvim-dap-ui but I'd rather avoid messing with the buffer if possible.
https://github.com/rcarriga/nvim-dap-ui/issues/214
https://github.com/rcarriga/nvim-dap-ui/commit/b3b977095877e8acc1ff236cffc81b5331619493#commitcomment-98160282
https://github.com/rcarriga/nvim-dap-ui/issues/165
https://github.com/rcarriga/nvim-dap-ui/issues/130
> feat(repl): set buflisted=false

- lua/dap/repl.lua
Allows users to override options in a FileType autocmd
> Set dap-repl filetype after all options are set

- doc/dap.txt
As someone very new to NeoVim, I was getting started using [kickstart.nvim](https://github.com/nvim-lua/kickstart.nvim).
As that is a Lua based init script, I couldn't understand how to adapt the VimL nnoremap commands presented in :help mappings into their Lua alternatives. Thankfully in aYoutube video I stumbled into the vim.keymap.set() syntax, but I think presenting both would help new folks out a lot.
Thanks for the amazing plugin!
> #833 - add Lua style example mappings to help

- doc/dap.txt
- lua/dap.lua
- lua/dap/progress.lua
- lua/dap/session.lua
- lua/dap/ui.lua
- lua/dap/ui/widgets.lua
- tests/server.lua
- tests/sessions_spec.lua
~~Still needs some work~~
New API:
- `dap.sessions()` to return active debug sessions
- `dap.ui.widgets.sessions` to show active debug sessions
Step functions will change the focus automatically if the currently
focused session is not stopped.
This should make common scenarios like debugging client + server where
you step from making requests on the client to receiving request on the
server convenient.
Note that this is unrelated to `startDebugging` support. The PR here is
about concurrent top-level sessions. `startDebugging` support will
introduce hierarchical sessions. (Probably including something like
`children` in the `Session` object)
- ~~If there is an active session, should `run_last` / `run` default to restart (terminate, run new), or should they default to run an additional …
> Add support for running concurrent debug sessions

- lua/dap.lua
- lua/dap/repl.lua
- lua/dap/session.lua
- lua/dap/ui.lua
- tests/repl_spec.lua
Closes https://github.com/mfussenegger/nvim-dap/issues/845 and https://github.com/mfussenegger/nvim-dap/issues/854
> Don't add extra newlines to REPL on output events

- .github/workflows/release.yml
- README.md
- nvim-dap-scm-1.rockspec
nvim-dap is a common dependency across Neovim plugins. Using luarocks may alleviate the need for users to specify their plugins' dependencies in their plugin manager (e.g., vim-plug or packer).
See also [this blog post](https://teto.github.io/posts/2021-09-17-neovim-plugin-luarocks.html) for details.
This PR adds a release workflow that publishes this plugin to [LuaRocks](https://luarocks.org/) whenever a tag is pushed, as well as a rockspec that can be used to release to the `dev` channel or install this plugin from source using the luarocks CLI.
For the release workflow to work, someone with a LuaRocks account will have to add their API key to this repo's secrets.
Note that I have added a shield to the readme that assumes the existence of an `mfussenegger/nvim-dap` LuaRocks module.
> Add support for LuaRocks + release workflow

- lua/dap/breakpoints.lua
- lua/dap/utils.lua
- tests/breakpoints_spec.lua
```
E5108: Error executing lua:
~/.local/share/nvim/lazy/nvim-dap/lua/dap/breakpoints.lua:187: invalid
value (boolean) at index 2 in table for 'concat'
stack traceback:
[C]: in function 'concat'
~/.local/share/nvim/lazy/nvim-dap/lua/dap/breakpoints.lua:187: in function 'to_qf_list'
~/.local/share/nvim/lazy/nvim-dap/lua/dap.lua:723: in function 'list_breakpoints'
...azy/telescope-dap.nvim/lua/telescope/_extensions/dap.lua:115: in function 'list_breakpoints'
~/.config/nvim/lua/plugins/dap/init.lua:76: in function <~/.config/nvim/lua/plugins/dap/init.lua:75>
```
> Fix listing breakpoints with go/delve

- lua/dap.lua
- tests/integration_spec.lua
- tests/server.lua
Otherwise repeated run_last will stop terminating the running session
Closes https://github.com/mfussenegger/nvim-dap/issues/878
> Reset `new` flag for run_last

- lua/dap/session.lua
- tests/sessions_spec.lua
Otherwise the session remains in memory longer than necessary and the
sessions widget continues showing the child session until the parent
session ends.
> Clear children from parent if child session closes

- lua/dap/protocol.lua
- lua/dap/session.lua
It doesn't need to have a path. Frames with source reference can be
fetched
> Use first frame with source as top-frame

- lua/dap/ui.lua
- tests/ui_spec.lua
Fix #888.  When `dap.ui.Layer.render` is called with `start == nil` and `end_ == nil`,  assign `start = 0` only when the buffer contains a single, empty line.  For all other cases, assign `start == line-count` instead of `start == line-count - 1`, which appears to be causing the line swapping issue.
Add a simple test case where the buffer already contains non-empty lines, and a new line is added with `start == nil` and `end_ == nil`, which should now be appended to the end.
> Fix lines in scope widget go under a wrong group 

- lua/dap/session.lua
- tests/integration_spec.lua
Some debug adapters allow to resume execution using custom evaluate
commands. This unfortunately by-passes some logic that puts the client
into "running" state again.
If the client then receives a stopped event it assumed it
was already stopped and sent a continue request (unless
`auto_continue_if_many_stopped` was disabled)
This changes the condition to also jump if `stopped_thread_id ==
stopped.threadId`
Closes https://github.com/mfussenegger/nvim-dap/issues/898
Co-authored-by: xac <jiangfengxi.c@gmail.com>
> Jump on stopped event if same threadId is already marked as stopped

- lua/dap.lua
- tests/integration_spec.lua
Closes https://github.com/mfussenegger/nvim-dap/issues/904
> Fix losing session ref when stepping without being stopped

- lua/dap/session.lua
- tests/server.lua
- tests/sessions_spec.lua
With this change `startDebugging` should work out of the box for debug
adapters configured with type=server and an executable.
For example, for vscode-js-debug, instead of a custom adapter factory
like:
```lua
require("dap").adapters["pwa-node"] = function(on_config, config, parent)
local target = config["__pendingTargetId"]
if target and parent then
local adapter = parent.adapter --[[@as ServerAdapter]]
on_config({
type = "server",
host = "localhost",
port = adapter.port
})
else
on_config({
type = "server",
host = "localhost",
port = "${port}",
executable = {
command = "node",
args = {"/path/to/js-debug/src/dapDebugServer.js", "${port}"},
}
})
end
end
```
It will be possible to use the simpler definition:
```lua
require("dap").adapters["pwa-node"] = {
type = "server",
host = "localhost", …
```
> Change startDebugging to connect to parent adapter if type=server with executable

- lua/dap/repl.lua
- lua/dap/session.lua
Currently starting a new session clears the REPL history. I see no reason why this is required, and actually I have found quite common the need to reuse REPL command between sessions.
Other IDEs (e.g. vscode) also keep history between sessions.
> remove REPL history clear when starting a new session

- lua/dap/session.lua
So far it set the cursor, but didn't change the active window.
See https://github.com/mfussenegger/nvim-dap/issues/980#issuecomment-1625103893
> Focus window with breakpoint on stopped event

- doc/dap.txt
- lua/dap/utils.lua
To show more processes. Otherwise it's restricted to terminal processes.
> Use `ps ah -u $USER` for `dap.utils.pick_process`

- doc/dap.txt
- lua/dap/utils.lua
> Use ps -U instead of ps -u

- doc/dap.txt
- lua/dap.lua
- lua/dap/session.lua
- tests/pipe_spec.lua
- tests/server.lua
For adapters like cmake which don't support stdin or TCP
Closes https://github.com/mfussenegger/nvim-dap/issues/924
For example:
local dap = require("dap")
dap.adapters.cmake = {
type = "pipe",
pipe = "${pipe}",
executable = {
command = "cmake",
args = {"--debugger", "--debugger-pipe", "${pipe}"}
}
}
dap.configurations.cmake = {
{
name = "Build",
type = "cmake",
request = "launch",
}
}
> Add support for unix domain sockets and named pipes

- lua/dap/breakpoints.lua
- lua/dap/session.lua
When severity_sort is enabled, diagnostic sign priority can be raised above 10 (1 per severity). And so by putting it at 21 and 22, dap breakpoints are always shown, even when there are diagnostics
(Related to #197 )
> Increase priority of signs

- lua/dap.lua
Hi,
I mostly use DAP to debug a long-running server process. My workflow has me closing Vim frequently, and whenever I do without remembering to disconnect the debugger, I accidentally terminate the server. Is that intended behavior? Why would DAP want to manage the lifecycle of an "attached" debugee?
Anyways, this hack seems to fix it for me. This was the smallest change I could think of, but it's a breaking change. Perhaps it would be better placed as a per configuration option (`terminate_on_vim_exit = false` or `on_vim_exit = "terminate" | "disconnect"`), which defaults to termination, but allows opting out?
I'm not particularly attached to any of this. Take it or leave it, or modify it as you see fit :)
Thanks for your work on this plugin 👍
> Stop terminating "attached" debugees when exiting Vim

- lua/dap/protocol.lua
- lua/dap/repl.lua
Doesn't handle mixed cases yet but should fix the cpptools case
mentioned in https://github.com/mfussenegger/nvim-dap/issues/1037
> Handle length/start in completions response in repl.omnifunc

- lua/dap/session.lua
On Windows, when using a server type debug adapter that is executed (in this case codelldb) I received the following warning after a debug session ended:
> ...codelldb.CMD exited with code 1
Changing "sigterm" to "SIGTERM" in the client close function fixes this.
> fix: Exit code 1 warning at the end of a debug session on Windows

- lua/dap/entity.lua
`_frame_set` changes the buffer and then `vim.bo.bufhidden` returned the
wrong value.
> Ensure threads floating win closes on frame selection

- lua/dap/ui.lua
Fixes #1042.
This is a really naive approach at solving the problem and I'm not sure if this somehow affects other places in the codebase. Since `layer.render` is being called without a parameter for `lnum` and `end_` inside each widget, the render function appends the widget content instead of replacing it (wich does happend when the widget ir refresh. I saw that in that call 0 and -1 were being passed as values for `lnum` and `end_`, so I tried doing the same here and it worked).
> fix: do not append text each time a widgets is opened

- lua/dap/repl.lua
Here is a few things I learned along the way and how I approached fixing #1052.
* REPL buffer is based on `buftype=prompt`, where nvim makes sure that there is always a prompt at the end of buffer in insert mode (`dap> ` ).
* When a new command is entered, `exec` function in `repl.lua` is executed (registered via `vim.fn.prompt_setcallback`). nvim does not put the next prompt until callback returns, so, within the callback, new lines can simply be appendend at the end of the buffer. (e.g. `.help` command does not leave an empty prompt in the middle).
* Things get a bit tricky with expression command because when a DAP server request comes back, nvim-dap is aldready outside of the callback, and there is an empty prompt at the end of the buffer. Two options here so not to leave an empty …
> Fix repl expressions leave an empty prompt in the middle (#1052)

- lua/dap.lua
Problem: Any exceptions thrown inside coroutine-wrapped `trigger_run`
inside `dap.run()` are silenced. Dap session won't start silently
without any error messages displayed to users.
Solution: Protect the call of `trigger_run` and show error messages with
stacktrace, if any errors happened.
> Show error messages when the coroutine in trigger_run throws an error

- lua/dap/ui.lua
- lua/dap/ui/widgets.lua
`lnum` and `end_` need to be set to `nil` when appending additional scopes to the widget, otherwise the final scope overwrites all previous ones. In the case of `lldb`, where you have 'Local', 'Global', and 'Registers', only the last scope 'Registers' would be drawn to the widget.
> Stop always replacing with last scope

- lua/dap/entity.lua
- lua/dap/protocol.lua
As described in https://github.com/mfussenegger/nvim-dap/issues/1062
Some debug adapters heavily use the lazy hint.
For example, a collapsed list is initially displayed as:
settings: ArrayList@50 size=1
That's good. But after expanding, the contained items looke like this:
settings: ArrayList@50 size=1
0: Assignment@66
Each individual item had to be expanded to show the value:
settings: ArrayList@50 size=1
0: Assignment@66 "Assignment{column='stats.jobs_log_size', expressions=[1024]}"
This removes the intermediate step, to go from:
settings: ArrayList@50 size=1
Straight to:
settings: ArrayList@50 size=1
0: Assignment@66 "Assignment{column='stats.jobs_log_size', expressions=[1024]}"
> Eagerly load lazy variables when expanding children

- lua/dap.lua
- lua/dap/progress.lua
nvim-dap reports `Launching debug adapter` before evaluating a adapter
function:
progress.report('Launching debug adapter')
But that message was never shown in `dap.status()` because at that point
no session is active and `status()` returned a `''`.
If the adapter function takes a long time, it gave
the impression that nothing was happening.
Solution:
Always show the last message in `status()`, and send a `""` if a session
closes.
> Ensure dap.status() shows start progress

- doc/dap.txt
The term "hot-link" comes from |help-writing| in helphelp.txt.
> Fix hot-link in dap.txt

- doc/dap.txt
- lua/dap.lua
- lua/dap/session.lua
5000ms can be too short.
See https://github.com/mfussenegger/nvim-dap/discussions/1147
> Allow to configure max wait timeout for pipe adapter

- lua/dap/session.lua
- tests/debugpy_spec.lua
Some debug adapters don't like it if dap closes stdin eagerly.
An example is gdb: https://github.com/mfussenegger/nvim-dap/issues/1206
> Close stdio handles after process exits

- lua/dap/ui/widgets.lua
10 levels can take a huge amount of time to load, and there's currently
no way to interrupt it.
modified=false and bufhidden=wipe should make it easier to get rid of
the buffers after being done viewing the diff.
> Tweak buffer settings for variable diff view; lower max_level to 1

- doc/dap.txt
- lua/dap/utils.lua
This implements a file picker, to pick the file you want to execute with the debugger.
Fixes #1130
> feat(utils): Implement pick_files()

- lua/dap/utils.lua
Should fix https://github.com/mfussenegger/nvim-dap/issues/1220
> Handle paths relative to custom path in utils.pick_file

- lua/dap/repl.lua
- lua/dap/ui/widgets.lua
Seems to work better for variables where the `tostring` implementation
is long and repeats information also available in the structure display.
> Set nowrap in repl and float windows

- doc/dap.txt
- lua/dap.lua
- lua/dap/ext/vscode.lua
- Introduces a dap.providers.configs table which plugins can extend to
add additional sources for dynamic configuration generation
- Implements the two built-in configuration sources as providers
- `.vscode/launch.json` files are now loaded automatically by one of
these providers. The entries from the file always display even if the
type doesn't match the current filetype. This gets rid of the
`type_to_filetypes` mapping requirements.
Closes:
- https://github.com/mfussenegger/nvim-dap/issues/1065
- https://github.com/mfussenegger/nvim-dap/issues/1087
- https://github.com/mfussenegger/nvim-dap/issues/1226
> Add config providers; always load .vscode/launch.json

- plugin/dap.lua
The files are now instead loaded on-demand if a session is spawned
> Drop BufWritePost for .vscode/launch.json files

- plugin/dap.lua
If no args: calls dap.continue({ new = true })
If args: calls dap.run for each configuration where name=arg
E.g.: `:DapNew celery django`
If config names contain spaces they need to be escaped
> Add :DapNew command start new session

- doc/dap.txt
- lua/dap.lua
Fits a bit better and there may be other client generated events in the
future.
> Move on_config hooks from providers to listeners

- spec/ext_vscode_spec.lua
To allow plugins to process them using a `dap.listeners.on_config` hook
> Ensure ${input:} placeholders with unknown types are left untouched

- plugin/dap.lua
Creates a new window with a `dap-eval://` scratch buffer
Supports range mode to pre-fill it with the selected content.
Supports bang to immediately evaluate the content
This is a variant addressing https://github.com/mfussenegger/nvim-dap/issues/665
> Add DapEval command

- lua/dap/ext/vscode.lua
When launch.json has invalid encoding/bom launch.json can not be parsed, but it seems that assert does not catches it, so there is a general error message about can not parsing the json, instead of the message that there is some kind of problem with launch.json
To reproduce (tested on Linux):
```
:set ff=unix
:set bomb
```
This PR fixes this behaviour. Currently it also shows the whole launch.json, so the `<feff>` is very telling. If it is too much I can revert to the original message. Maybe extending it with a hint that BOM might be the source of the error.
> Fix only general error message is shown when launch.json is invalid

- lua/dap.lua
If you have multiple sessions `continue()` should resume an unfocused
session instead of telling the user that the current session is not
stopped at a breakpoint.
> Change continue() to resume other session if focused session is not stopped

- lua/dap/session.lua
This PR fixes #1317
and correctly passes environment variables to the program
> Fix run in external terminal not propagating environment variables to program

- lua/dap/session.lua
Fix https://github.com/mfussenegger/nvim-dap/issues/956#issuecomment-1584883229
The disassembly buffer is of the "nofile" type, which has not been handled. This leads to the error "cursor position outside the buffer" when more than two panes opened.
This error can be reproduced using [this Dockerfile](https://github.com/bogdan-nikitin/nvim-dap-956/blob/main/Dockerfile):
1. Run container interactively. Neovim opens with an example file with a breakpoint set
2. Type `:DapContinue`
3. Type `:DapStepInto` few times
4. Assembly will appear in both panes
> Handle disassembly buffer

- doc/dap.txt
- lua/dap/session.lua
Closes https://github.com/mfussenegger/nvim-dap/issues/1328
> Add a `usevisible` switchbuf option

- lua/dap/session.lua
Problem:
A debug adapter can respond to goto with an error - e.g. if attempting
to jump to a location where there is no code to execute.
If that happened, selecting another goto location was no longer possible
because the stopped state had been cleared.
Solution:
Restore stopped state if goto fails
> Restore stopped state if goto errors

- lua/dap/session.lua
This was discussed on the closed issue #1317 (from [this comment](https://github.com/mfussenegger/nvim-dap/issues/1317#issuecomment-2373653869)).
#1318 was merged in August and propagated environment to the launched external terminal, but it seemed to propagate the environment VIM was started with **if and only if** an environment was set somewhere in the configuration and passed to the `launch_external_terminal` function.
This had the side effect, under some configuration, that the launched external terminal have an empty environment.
This pull request changed the logic when merging VIM environment and passed environment to always include the environment VIM was started with.
--
I am quite unable to determine if this could have side effects or if the fact that the parent environment not …
> Always inherit environment when launching external terminal

- lua/dap/session.lua
- spec/integration_spec.lua
> fix: check if thread is still paused before handling stacktrace command result

- lua/dap/session.lua
See clarification: https://github.com/microsoft/debug-adapter-protocol/pull/514
> Handle absent `allThreadsContinued` as true

- lua/dap.lua
- lua/dap/protocol.lua
- lua/dap/repl.lua
- lua/dap/ui.lua
- lua/dap/ui/widgets.lua
Requires debug adapters to set the `valueLocationReference` on evaluate
responses or `declarationLocationReference` on variables
> Add tagfunc for variables and expressions

- plugin/dap.lua
With the new config provider model the files are read implicitly
on-demand.
> Remove DapLoadLaunchJSON user command

- lua/dap.lua
- lua/dap/protocol.lua
- lua/dap/session.lua
Looks like debug adapters like js-debug-adapter take a bit to process
terminate requests. The `vim.wait(500, ...)` was not enough, leading to
leaked processes.
Lowering the terminate/disconnect request timeout appears to solve the
issue as it leads to the handle getting closed quicker.
Fixes https://github.com/mfussenegger/nvim-dap/issues/1352
> Lower timeout for terminate/disconnect request on nvim exit

- lua/dap/_cmds.lua
- lua/dap/repl.lua
- lua/dap/ui/widgets.lua
Easier to use than the "Copy as expression" menu action item, and
shouldn't get in the way either
> Yank expression's evalname automatically to `e` register on regular yank

- lua/dap/ui.lua
- lua/dap/ui/widgets.lua
Closes https://github.com/mfussenegger/nvim-dap/issues/1163
> Freeze expr provided to preview widget

- doc/dap.txt
- lua/dap.lua
- lua/dap/session.lua
First, I want to express my gratitude for your incredible contributions to the Neovim ecosystem.
In my current Neovim setup using `nvim-dap` for debugging, I utilize a custom console by defining a `terminal_win_cmd`.  However, with the existing implementation, there's a limitation: the callback function for `terminal_win_cmd` does not receive the debugging session's configuration. This makes it challenging to dynamically set the name of the integrated terminal based on the current debugging session, I need to set a name for the terminal on a multi-session scenario, enabling better picker search by name.
Modified the `terminal_win_cmd` callback to accept the `config` parameter. This allows the callback function to access details about the current debugging session, enabling dynamic naming …
> Allow terminal_win_cmd Callback to Receive Configuration.

- lua/dap/session.lua
Relates to https://github.com/mfussenegger/nvim-dap/issues/1416
> Use 'columns' and 'lines' based fallback for terminal win width & height

- lua/dap/utils.lua
I have outline the proposal behind this PR in #1431. 
Brief recap is to make `dap.utils.pick_process` more customizable by allowing for custom process labels and custom prompt.
When refactoring I opted to leave `cols` and `wordlimit` variables from #1403 outside default label function as they don't need to be calculated for every process.
> Customizable `dap.utils.pick_process` 

- lua/dap/log.lua
Un the current implementation, it will only log the caller function. The _log caller function is the level wrapper function,
Therefor we set the level to 3 to get  the caller(level) caller(actual caller) function info.
More info here
https://www.lua.org/pil/23.1.html
and here 
https://www.lua.org/manual/5.4/manual.html#pdf-debug.getinfo
> Use the correct caller fileinfo 

- lua/dap.lua
Addresses issue where setting dap.defaults[ft]autostart = "config" uses "dap-repl" as filetype when attempting to start config from using repl and there is no active session
> fix: set source filetype in providers.configs

- plugin/dap.lua
if you passed a space after the level it should just work you did not add any letters and its not a script.
In example if you typed:
“DapSetLogLevel DEBUG “
it will not work,
So I trimmed the function args, I also replaced `unpack(opts.fargs)` with `opts.args` because it will return the same result with less code 
Note:
`opts.fargs` is table of the function args.
`unpack(table)` convert table to string.
`opts.args` is args as string.
reference: https://neovim.io/doc/user/api.html#nvim_create_user_command()
> Fix DapSetLogLevel when passing space after the level

- lua/dap/session.lua
- spec/integration_spec.lua
Alternative to https://github.com/mfussenegger/nvim-dap/pull/1469
The `response.body` was reused as `response` despite having an error set
based on `success=false`
> Ensure response handler are called with response=nil if there is an error

- .github/workflows/tests.yml
- README.md
For users of nvim 0.9.5 - I suggest pinning to nvim-dap to [0.10.0](https://github.com/mfussenegger/nvim-dap/releases/tag/0.10.0)
> Drop support for nvim-0.9.5; add support for 0.11.0

- lua/dap.lua
Hey!
When trying to use the `enrich_config` property, I noticed that adding fields to the configuration creates a lua-ls warning:
```
Fields cannot be injected into the reference of `dap.Configuration` for `foo_bar`. To do so, use `---@class` for `config`. 
```
Since configurations can hold pretty much arbitrary data (by nesting), I decided to update the annotation accordingly.
> Support arbitrary fields in dap.Configuration annotation

- lua/dap/session.lua
This PR is a continuation of #1488, where I explored some nvim-dap terminal issues—specifically, wrong scrollback handling and the cursor not changing its shape when debugging Neovim. Resizing problems, as I found out, were due to the debug adapter, so this PR doesn’t fix those.
While continuing to use it, I faced other issues with this terminal. I launched tests in my project, and for some reason, the test output didn’t have colors. With this patch, all three issues I found disappeared. It also remove the fragile nvim_chan_send logic and lets neovim handle it itself, which I think is always for the best. The 'Process exited' and 'CR' used to delete the buffer at the end are also removed because neovim :terminal already handles them
So this patch makes the nvim-dap-provided terminal …
> replace nvim_open_term with vim.jn.jobstart(..., {term = true})

- lua/dap.lua
Good afternoon.
I've noticed that `nvim-dap` does not display error messages when parsing `launch.json`, so it's difficult to understand the cause of possible problems.
I suggest adding an error message, in my case it looks like this:
```
Cannot get configurations from `launch.json`:
...\Local\nvim-data\plugged\nvim-dap/lua/dap/ext/vscode.lua:150: Error parsing launch.json: Expected object key string but found T_OBJ_END at character 1180
```
> Show notification for launch.json parsing errors

- lua/dap/session.lua
Hello.
After #1490 was merged, the terminal buffer name becomes the command name instead of the  `[dap-terminal] ...` format, like this.
I find out that the terminal buffer name was being incorrectly overwritten after `vim.fn.jobstart` called.
Fixed by setting terminal buffer name after `vim.fn.jobstart`.
> Fix terminal buffer name incorrectly overwriten by vim.fn.jobstart

- doc/dap.txt
The documentation for vim help pages states that a first line is required for the file to appear under :help local-additions, with the following format: *tag* description
This change modifies the first line to follow that format
> Fix first line in doc for local-additions

- lua/dap/session.lua
Implements https://github.com/mfussenegger/nvim-dap/discussions/1523#discussioncomment-14215672
Alternative to #1519 
**Problem**: UI plugins need to accurately retrieve the terminal buffer for the current session, so they can show the corresponding buf.
**Solution**: add an optional field to `dap.Session` that stores the buffer.
By the way, I'm planning on making some more contributions, would you prefer if new PRs were opened on codeberg?
> Retrieve `term_buf` by session
