mfussenegger/nvim-dap

- lua/dap.lua
Requires https://github.com/neovim/neovim/pull/11839 to work with
requests that require `env` options. (Which is the case for debugpy)
> Support runInTerminal request

- lua/dap.lua
- lua/dap/repl.lua
Thanks for this awesome plugin. I really appreciate that it's goal is to hackable (and it already).
I was only missing a way to configure the repl commands. So I added a `plugin_config` module (`plugin_confg` to distinguish config for debuggers/debugees). There maybe a better way to organize this.
> Add a way to configure repl commands

- lua/dap.lua
I guess you renamed: `_set_frame` to `_frame_set`.
This PR fixes up/down for that change.
> Fix up/down: _set_frame -> _frame_set

- autoload/dap.vim
- lua/dap/repl.lua
Possible with https://github.com/neovim/neovim/commit/971a191c4d772493535d55524b994fe385fae546
> Use lua function ref in prompt_setcallback

- lua/dap.lua
This enables extensions to nvim-dap both defined either by end users or
by plugin developers. This enables me to implement
https://github.com/mfussenegger/nvim-dap/pull/13 as an external plugin.
Usage to hook into `event_continued`:
```lua
if dap.custom_event_handlers then
table.insert(dap.custom_event_handlers.event_continued, function(session, body)
dap.repl.append(vim.inspect(body))
end)
end
```
or
```lua
dap.custom_event_handlers.event_exited["my handler id"] = function(_, _)
dap.repl.close()
end
```
If this PR has your general ok. I could implement the external plugin to see if these changes are reasonable.
> Add support for user-defined `custom_event_handlers`

- lua/dap.lua
Fix ordering of custom_response_handlers
Custom handlers must be schedule_wrapped together with the original
callbacks to get any guarantees on ordering.
Fixes https://github.com/theHamsta/nvim-dap-virtual-text/issues
I also added the original request to for the custom_response_handlers in case they need the original request to interpret the response. This is a separate commit and not necessary to fix the problem but the additional information might become handy in future.
> Fix ordering of custom_response_handlers

- doc/dap.txt
- lua/dap/repl.lua
Adds a `.capabilities` command and the possibility to add own `custom_commands`. Probably, the code could be refactored to implement all commands in the way of `custom_commands`.
> Custom repl commands

- doc/dap.txt
- lua/dap.lua
This function allows adapters to enrich a configuration with additional
properties before running both adapter and configuration.
> Add enrich_config function for adapters

- lua/dap/repl.lua
Maybe this should also allow expansion of further nested attributes via `<CR>`, similar to how it works on the frames?
> Expand variables with structure after evaluate in REPL

- README.md
- doc/dap.txt
- lua/dap.lua
- lua/dap/repl.lua
I needed to pause a long running job today.
> Add 'pause' functionality

- lua/dap.lua
See https://github.com/neovim/neovim/pull/13288
> Reduce string concat related allocations

- doc/dap.txt
- lua/dap.lua
Useful for other extensions, see https://github.com/nvim-telescope/telescope-dap.nvim/pull/1
> Expose current session

- lua/dap.lua
An example where this is required is the debug_selection functionality
in https://github.com/mfussenegger/nvim-dap-python
> Load source on breakpoint if sourceReference > 0

- lua/dap.lua
Should help users spot configuration errors
> Assert that configurations is list like, not an object

- doc/dap.txt
> Extend documentation

- README.md
- Rearrange the sections.
- Extend some of the sections.
> Tweak README a bit

- doc/dap.txt
- lua/dap/ui/variables.lua
See https://github.com/mfussenegger/nvim-dap/pull/97#pullrequestreview-581756680
> variables: add visual_hover for evaluating visual selection

- doc/dap.txt
- lua/dap/ui/variables.lua
Add a hover window for variable scopes
> variables: add scopes hover

- lua/dap.lua
- lua/dap/rpc.lua
Subset of https://github.com/mfussenegger/nvim-dap/pull/114
> Extract rpc logic into a separate module

- .github/workflows/tests.yml
- tests/minimal.vim
- tests/utils_spec.lua
The basic utils tests that this adds are mostly to get the testing setup
bootstrapped.
> Add tests to CI

- lua/dap.lua
- lua/dap/breakpoints.lua
- tests/breakpoints_spec.lua
Another subset of https://github.com/mfussenegger/nvim-dap/pull/114
> Extract parts of breakpoint logic into a dedicated module

- lua/dap.lua
So that users get some feedback and have an idea on what's going on.
> Add some progress notifications when launching a session

- lua/dap.lua
- lua/dap/session.lua
I'm not entirely sure if this is a good idea.
> Prompt user with choices on continue if not stopped at thread

- lua/dap/repl.lua
- lua/dap/session.lua
- lua/dap/ui.lua
- tests/ui_spec.lua
Should allow to re-use some of the logic for other data
> repl: Decouple frames from extmark/printing/re-printing

- lua/dap/repl.lua
- lua/dap/ui.lua
Next step after this would be to extract some common `variables` widget that can be used in both the repl and the variables ui.
> Make variables in REPL expandable

- lua/dap/session.lua
See commits.
Should close https://github.com/mfussenegger/nvim-dap/issues/177
> Improve capabilities handling

- lua/dap/session.lua
This will allow extensions to listen to events that are not part of the
core specification, or to events where nvim-dap don't have a default
implementation yet.
> Invoke custom listeners even if there is no default callback

- lua/dap/repl.lua
Was suggested by @theHamsta. Closes #187.
> Preprocess Windows encoding

- doc/dap.txt
- lua/dap.lua
- lua/dap/breakpoints.lua
- lua/dap/session.lua
Closes https://github.com/mfussenegger/nvim-dap/issues/188
> Add a run_to_cursor function

- lua/dap.lua
On my machine this decreases the time for `require('dap')` from ~4ms to ~1ms
> Lazy load internal modules

- lua/dap/session.lua
This avoids window resizes if the terminal is already open
> Re-use terminal window if already open

- lua/dap/ext/vscode.lua
In a debugee configurations, the `type` field refers to an adapter
defined in `dap.adapters.<adapter-name>`. Current implementation has
an assumption that the `config.type`, which is the name of an adapter,
is the same as a debugee name. Therefore it is used for retrieving a
debugee configurations as a key of `dap.configurations[config.type]`.
The assumption works in most cases, since most adapter-debugee gets the
same name for which a simple "filetype" is often chosen, such as php or
python. One example breaks the rule is lldb adapter. There is a mismatch
between the adapter lldb and its multiple debugees like c++ and rust.
This commit simply groups filetypes by adapaters to fix it.
> Accept adapter/debugee with different names in launch.json

- lua/dap.lua
- tests/integration_spec.lua
Fixes https://github.com/mfussenegger/nvim-dap/issues/228
> Expand config variables recursively

- lua/dap.lua
- lua/dap/session.lua
Fixes https://github.com/mfussenegger/nvim-dap/issues/238
> Send SIGTERM to debug adapter if session is closed

- doc/dap.txt
- lua/dap/ui.lua
- lua/dap/utils.lua
Can be used in configurations to attach to processes.
> Add a `pick_process` util function

- lua/dap/ui.lua
- tests/ui_spec.lua
There can be more lines with text
Follow up to https://github.com/mfussenegger/nvim-dap/pull/246
> Don't abort loop in layer.render on empty text

- doc/dap.txt
- lua/dap.lua
- lua/dap/session.lua
> Add id to adapter definition

- lua/dap.lua
Closes https://github.com/mfussenegger/nvim-dap/issues/274
> Raise more user friendly errors in dap.run

- lua/dap/session.lua
Although the luv documentation states that `on_exit` is called when the
child process exits, that doesn't seem to be the case if the process
gets terminated via `handle:kill(15)`.
Additionally, the stdio pipes weren't closed if the handle assertion
triggered.
Should fix https://github.com/mfussenegger/nvim-dap/issues/287
> Ensure stdio descriptors get closed

- lua/dap/ui.lua
Fixes a regression introduced in https://github.com/mfussenegger/nvim-dap/pull/280
> Fix utils.notify call / log.levels reference in dap.ui

- lua/dap/session.lua
Motivated by https://github.com/mfussenegger/nvim-dap/discussions/296
> Write telemetry output events to info log instead of REPL output

- lua/dap/progress.lua
> fix(status): remove config type check on status

- lua/dap/ui.lua
Requires https://github.com/neovim/neovim/pull/15819
> Use vim.ui.select for pick_one if available

- doc/dap.txt
- lua/dap.lua
- lua/dap/breakpoints.lua
> feat(breakpoint): add conditional breakpoint sign define

- lua/dap/entity.lua
The `variablesReference` must point to the parent container, not to the
variable whose value you want to change.
> Fix `Set variable` action

- lua/dap.lua
Fixes https://github.com/mfussenegger/nvim-dap/issues/369
> Ensure `${relativeFileDirname}` is relative

- lua/dap.lua
- tests/integration_spec.lua
Closes https://github.com/mfussenegger/nvim-dap/issues/374
> Expand variables in keys of nested tables in configurations

- lua/dap/session.lua
For more context you can look at my comment here: https://github.com/mfussenegger/nvim-dap/discussions/314#discussioncomment-1782131
I wasn't sure if you wanted this explicitly stated int he docs since this might be sort of niche. Let me know your thoughts!
> feat: add a sec_to_wait config value to delay warning

- lua/dap.lua
Should fix https://github.com/mfussenegger/nvim-dap/issues/388
> Terminate active session when closing vim

- lua/dap/session.lua
So far only IPs were supported.
Closes https://github.com/mfussenegger/nvim-dap/issues/395
> Support host names as `host` in server adapters

- lua/dap/ext/vscode.lua
> perf: use vim.json if possible for launch.json

- lua/dap/repl.lua
Alternative approach to https://github.com/mfussenegger/nvim-dap/pull/403
Keeps outputting the raw data if presentation hint is present or if the
response is structured.
> Split newlines from REPL evaluate if text

- lua/dap/session.lua
Closes https://github.com/mfussenegger/nvim-dap/issues/422
> Allow replacing scratch buffers when jumping to frame

- lua/dap/ui/widgets.lua
Closes https://github.com/mfussenegger/nvim-dap/issues/428
> Set cursor initially on first line in hover widget

- lua/dap.lua
Fixes https://github.com/mfussenegger/nvim-dap/issues/459
> Wait for disconnect response before closing session

- .luacheckrc
- lua/dap/session.lua
- tests/integration_spec.lua
- tests/server.lua
Closes https://github.com/mfussenegger/nvim-dap/issues/478
> Handle duplicate session close calls

- lua/dap/session.lua
- tests/integration_spec.lua
Closes https://github.com/mfussenegger/nvim-dap/issues/475
Closes https://github.com/mfussenegger/nvim-dap/issues/469
A consequence of this change is that even for the debug adapters that do
send a terminated event after receiving a disconnect request (like
java-debug), this event might not be received anymore because the
session is closed after the disconnect response.
Extensions that want to run some logic if a debug session ends
should listen to both `event_terminated` and `disconnect`.
@theHamsta @rcarriga fyi I think this might affect your plugins
> Close session on disconnect response

- doc/dap.txt
- lua/dap/session.lua
- tests/integration_spec.lua
See https://github.com/mfussenegger/nvim-dap/issues/334
> Allow to set a default source filetype per adapter

- lua/dap/session.lua
- tests/integration_spec.lua
Closes https://github.com/mfussenegger/nvim-dap/issues/522
Closes https://github.com/mfussenegger/nvim-dap/issues/525
> Fix fallback in get_top_frame (Fixes Attempt to index local 'frame' (a number value))

- lua/dap/session.lua
- tests/integration_spec.lua
Closes https://github.com/mfussenegger/nvim-dap/issues/426
> Clear breakpoints if a buffer is deleted

- lua/dap/repl.lua
Fixes https://github.com/mfussenegger/nvim-dap/issues/545
Fixes https://github.com/mfussenegger/nvim-dap/issues/546
> Handle custom commands in omnifunc and help

- lua/dap/session.lua
- tests/integration_spec.lua
Workaround for https://github.com/mfussenegger/nvim-dap/issues/552
> Jump to stopped location if pause & allThreadsStopped

- lua/dap/session.lua
> set empty callback if no callback given

- lua/dap.lua
`stopped_thread_id` indicates the thread where the debugger is currently
stopped, but if multiple threads were hitting the breakpoint multiple
threads can be stopped.
This changes continue to show a prompt to select other stopped threads
if the "main" thread was already resumed.
> Let continue resume paused threads

- lua/dap/session.lua
Closes https://github.com/mfussenegger/nvim-dap/issues/609
> Fix goto_ handling (clear stopped flags)

- lua/dap/session.lua
Should resolve https://github.com/mfussenegger/nvim-dap/issues/575
https://user-images.githubusercontent.com/38700/180186504-0127a6e1-5144-4552-92b4-b610284a8331.mp4
> Add thread selection on step if no paused thread has focus

- lua/dap/session.lua
`detach_handlers` is global and by the time a buffer is deleted a new
session might be active.
> Avoid keeping a session reference in breakpoint detach handlers

- doc/dap.txt
- lua/dap.lua
- lua/dap/session.lua
Should solve https://github.com/mfussenegger/nvim-dap/issues/641
> Increase amount of connect retries; expose setting

- lua/dap/session.lua
Mostly to match the emmylua type annotations
> Set empty capabilities when session is created

- lua/dap/repl.lua
Closes https://github.com/mfussenegger/nvim-dap/issues/702
> Add .clear repl command

- lua/dap.lua
- lua/dap/session.lua
Closes https://github.com/mfussenegger/nvim-dap/issues/699
> Log error on no callback and don't trigger listeners

- doc/dap.txt
- lua/dap.lua
- lua/dap/session.lua
- plugin/dap.lua
- tests/integration_spec.lua
Allows to restart execution of the current frame
https://user-images.githubusercontent.com/38700/194747820-7ad3a2eb-bf7f-4238-a333-e2a4189a6666.mp4
> Add restart_frame function and DapRestartFrame command

- doc/dap.txt
- lua/dap/session.lua
Closes https://github.com/mfussenegger/nvim-dap/issues/797
> Support calling continue and step with a count

- doc/dap.txt
- lua/dap/ext/vscode.lua
- tests/ext_vscode_spec.lua
Closes https://github.com/mfussenegger/nvim-dap/issues/794
> Support system specific properties in launch.json

- doc/dap.txt
- lua/dap.lua
- lua/dap/session.lua
- tests/debugpy_spec.lua
Follow up to https://github.com/mfussenegger/nvim-dap/pull/789
Should close:
- https://github.com/mfussenegger/nvim-dap/issues/793
- https://github.com/mfussenegger/nvim-dap/issues/676
> Add switchbuf setting to control jump to breakpoint behavior

- doc/dap.txt
- lua/dap.lua
Closes https://github.com/mfussenegger/nvim-dap/issues/796
> Add a `focus_frame` function

- lua/dap/repl.lua
Closes https://github.com/mfussenegger/nvim-dap/issues/640
> Add autoscroll for the REPL

- lua/dap.lua
- lua/dap/ext/vscode.lua
- lua/dap/session.lua
> Remove vim.json compat layer

- lua/dap/session.lua
- tests/integration_spec.lua
Closes https://github.com/mfussenegger/nvim-dap/issues/829
> Fix jumping to frame where source must be fetched

- lua/dap/session.lua
Will be required for multi-session support. There might be multiple
terminal buffers in use at the same time.
> Add pooling for terminal buffers

- lua/dap.lua
Should make working with multiple sessions a bit less clunky
> Change active session on breakpoint; propagate breakpoint changes

- lua/dap.lua
> Remove BWC from attach

- lua/dap.lua
- lua/dap/entity.lua
- lua/dap/protocol.lua
- lua/dap/session.lua
- lua/dap/ui/widgets.lua
- tests/server.lua
- tests/sessions_spec.lua
Early prototype
~~Doesn't appear to be working yet - the specification is unfortunately a bit vague~~
https://user-images.githubusercontent.com/38700/218164604-797b2016-2cad-449f-93aa-475ef41ee79c.mp4
> Add `startDebugging` support

- lua/dap/session.lua
Closes https://github.com/mfussenegger/nvim-dap/issues/735
> Don't flip to end/start when moving frames up/down

- lua/dap/session.lua
The uv process handle was closed too early, running into https://github.com/libuv/libuv/issues/1911
Closes https://github.com/mfussenegger/nvim-dap/issues/868
> Fix defunct processes using server adapter executable

- doc/dap.txt
- lua/dap/ext/vscode.lua
- tests/ext_vscode_spec.lua
> Add  default and object options

- lua/dap.lua
- lua/dap/repl.lua
- lua/dap/session.lua
- lua/dap/ui.lua
- lua/dap/ui/widgets.lua
They are getting deprecated: https://github.com/neovim/neovim/pull/23670
> Replace calls to nvim[_buf|_win]_[gs]et_option

- lua/dap/ui.lua
> Allow title for winopts to widgets

- lua/dap/session.lua
- lua/dap/ui/widgets.lua
Follow up to https://github.com/mfussenegger/nvim-dap/pull/982
> Don't switch away from REPL on stopped event; Fix close/wipe handling in widgets

- lua/dap/session.lua
If the same buffer is open in multiple windows and one of them is
focused, use the focused window.
> Prioritize focused window in switchbuf useopen/usetab

- lua/dap/utils.lua
> Add semicolon to select prompt

- lua/dap/protocol.lua
- lua/dap/ui/widgets.lua
This makes the behavior consistent with the REPL
> Prioritize evaluate in expression widget over variable lookup

- lua/dap/ext/vscode.lua
- tests/ext_vscode_spec.lua
Closes https://github.com/mfussenegger/nvim-dap/issues/1040
> Use vim.ui.input for launch.json promptString

- doc/dap.txt
- lua/dap.lua
- tests/integration_spec.lua
Closes https://github.com/mfussenegger/nvim-dap/issues/1036
> Add dap.ABORT to allow config functions to abort session

- lua/dap/session.lua
Closes https://github.com/mfussenegger/nvim-dap/issues/1007
> Change text for breakpoint unverified log entries

- lua/dap/session.lua
Hi @mfussenegger, 
Thanks for all your work on this plugin.
Just a small PR to fixup the fields of the `initialize request`.
https://pub.dev/documentation/dap/latest/dap/InitializeRequestArguments-class.html
> Fix `initialize` request fields

- lua/dap.lua
- lua/dap/async.lua
- lua/dap/ui/widgets.lua
- lua/dap/utils.lua
> Add widget function to show diff of two expressions

- lua/dap.lua
- tests/integration_spec.lua
Fixes https://github.com/mfussenegger/nvim-dap/issues/1101
> Evaluate config on run_last if adapter supports restart

- lua/dap/utils.lua
This implements a feature request I recently made #1096. If you believe it makes sense then here is a PR which implements the proposed change.
> Moved filtering logic from `pick_process` to `get_processes`

- lua/dap/ext/vscode.lua
- tests/ext_vscode_spec.lua
Closes https://github.com/mfussenegger/nvim-dap/issues/1112
> Evaluate inputs in launch.json config only once per config use

- lua/dap/repl.lua
Fixes https://github.com/mfussenegger/nvim-dap/issues/1131
> Don't ignore count for G keymap in repl

- doc/dap.txt
This PR just adds a missing comma in the documentation
> Add missing comma

- lua/dap/entity.lua
- lua/dap/ext/vscode.lua
- lua/dap/protocol.lua
- lua/dap/session.lua
- lua/dap/ui/widgets.lua
- lua/dap/utils.lua
> Do less work on scope responses

- plugin/dap.lua
Hi hi, just a little proposal for a user command to request a disconnect from a debuggee without finishing it.
I found this useful when attaching adapters to a process.
Thanks for your work, cheers
> Add DapDisconnect command

- .github/workflows/release.yml
Might help with https://github.com/mfussenegger/nvim-dap/issues/1269
> Update luarocks-tag-release GHA to v7

- lua/dap/protocol.lua
- lua/dap/session.lua
Relates to https://github.com/mfussenegger/nvim-dap/discussions/869#discussioncomment-10058258
> Always set startFrame in stackTrace request

- lua/dap/session.lua
When running tests via the debugger it's common that the test output in
the terminal includes paths to files. By inheriting the `path` setting
from the config's filetype there's a good chance that functions like
`gf` will work.
> Inherit `path` setting for term buffer

- lua/dap/session.lua
- spec/integration_spec.lua
If the debug adapter sends continued right after stopped, before the
client retrieved the threads the continued change was lost.
Should fix https://github.com/mfussenegger/nvim-dap/issues/1365
> Fix race between stopped thread retrieval and continued event

- lua/dap/ui.lua
This reverts commit 6bf4de67dbe90271608e1c81797e5edc79ec6335.
See https://github.com/mfussenegger/nvim-dap/commit/6bf4de67dbe90271608e1c81797e5edc79ec6335#commitcomment-149376847
> Revert "Change widget/repl toggle to close and re-open if in was on other tabpage"

- lua/dap/session.lua
- spec/debugpy_spec.lua
Prevents an error from showing up after the debug session finished with
debugpy:
Fatal Python error: _enter_buffered_busy: could not acquire lock for
<_io.BufferedReader name='<stdin>'> at inter preter shutdown,
possibly due to daemon threads
> Send sigint after stdin is closed

- doc/dap.txt
- lua/dap.lua
Relates to https://github.com/mfussenegger/nvim-dap/issues/1166
> Add `all` and `hierarchy` flags to terminate

- doc/dap.txt
- lua/dap/ext/vscode.lua
Didn't reflect the changes made in https://github.com/mfussenegger/nvim-dap/pull/1237
> Update outdated launch.json docs

- lua/dap/session.lua
Should help making `:cgetbuffer` more useful
This additionally also moves the `path` infer logic, so it is applied
even if a custom `terminal_win_cmd` function is used.
> Infer errorformat for terminal buffer from previous buffer

- lua/dap/session.lua
Hey!
Follow-up to https://github.com/mfussenegger/nvim-dap/commit/ffb077e65259f13be096ea6d603e3575a76b214a
I'm developing a plugin where I'm using these requests, so I thought it would be nice to have annotations for them.
> Add overload type annotation for threads and stackFrame requests

- lua/dap.lua
- lua/dap/protocol.lua
Hello!
Another ant-sized PR, I hope you don't mind 😬 
[Spec](https://microsoft.github.io/debug-adapter-protocol/specification#Requests_Initialize)
> Add type annotations to initialize request
